baseURL: https://mydigitaldumpster.netlify.app/
languageCode: en-us
title: A big button
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Howdy partner.
    title: Welcome to Fedor's ugly webpage
  blog: {}
  contact:
    address:
      - city: Milky Way
        country: Solar system
        street: 3rd planet from the star
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: fsblinov@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (228) 000-1337 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found ツ. You got played like a fiddle!
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      - icon: fa-facebook
        label: Facebook
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      - icon: fa-instagram
        label: Instagram
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      - icon: fa-github
        label: GitHub
        url: https://github.com/FSBlinov
      - icon: fa-linkedin
        label: LinkedIn
        url: hhttps://www.youtube.com/watch?v=dQw4w9WgXcQ
  image: ''
  name: Fedor Blinov
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: homework 3
        title: Some cool confindende intervals
        url: projects/project1
      - image: pic02.jpg
        subtitle: hehe i did it
        title: More r markdown
        url: projects/project2
      - image: pic04.jpg
        subtitle: Hi there
        title: Bio
        url: blogs/bio
      - image: pic11.jpg
        subtitle: very witty! (not really)
        title: Quote of the day
        url: blogs/quote
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
